//
//      Kirill Kobelev, Moscow-Paris-Sammamish.
//  -------------------------------------------------
//   All rights reserved. Commercial use without written permission prohibited.
//

#define    STRICT
#include  <stdio.h>
#include  <windows.h>
#include  <assert.h>

#include  "TextScan/Project.H"

// --------------------------------------------------------------------
//   ===================  TBasicProject  =====================
// --------------------------------------------------------------------


